### ISSUE TITLE
Pawn pieces not highlighted in JSON Editor

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#1273]
Somehow in #1245 we missed that pawn pieces are not being yellow highlighted in the room when selected. @rogerl50, I guess this is one more tweak you can make to your highly acclaimed enhancement.  I didn't see anything obvious to me in the code from 1245 that would be the source for this minor issue.

**Comment by RaphaelAlvez** [comment]
I got this by accident but I tempted to add it

![image](https://user-images.githubusercontent.com/73476656/179373880-979fd5be-b702-46a5-8363-4281d83da687.png)

**Comment by rogerl50** [comment]
@robartsd @ArnoldSmith86 The CSS class is getting set properly, but it's not taking effect for the pawns only. The other elements in that column of the edit window, if added to the room, highlight properly. Someone who really understands how various css elements interact needs to look at this. How annoying.

**Comment by rogerl50** [comment]
> I got this by accident but I tempted to add it
> 
> ![image](https://user-images.githubusercontent.com/73476656/179373880-979fd5be-b702-46a5-8363-4281d83da687.png)

Can you reproduce it and give us a room?

**Comment by RaphaelAlvez** [comment]
> > I got this by accident but I tempted to add it
> > ![image](https://user-images.githubusercontent.com/73476656/179373880-979fd5be-b702-46a5-8363-4281d83da687.png)
> 
> Can you reproduce it and give us a room?

that's on my computer. I'm trying to figure out how to overcome the mask. I was trying to add if to the before or after elements. probably we will need to cut the mask

**Comment by rogerl50** [comment]
Ah. Is it the mask that is causing the lack of highlighting?

**Comment by RaphaelAlvez** [comment]
well, am I going crazy?

I just went back to the main server an it is working
![image](https://user-images.githubusercontent.com/73476656/179374770-ba47a78e-4615-4745-b335-5b3e4d93bb39.png)

**Comment by RaphaelAlvez** [comment]
> Ah. Is it the mask that is causing the lack of highlighting?

yes. it seems like we can use some rectangle to limit the mask to the size of the object and then the border can appear

**Comment by RaphaelAlvez** [comment]
ok... so somehow I fixed it in one pawn and now I need to figure out what is the difference

**Comment by RaphaelAlvez** [comment]
please ignore all my previous comments. nothing was fixed. I was selecting an invisible widget that was above the pawn.....

**Comment by 96LawDawg** [comment]
> well, am I going crazy?
> 
> I just went back to the main server an it is working ![image](https://user-images.githubusercontent.com/73476656/179374770-ba47a78e-4615-4745-b335-5b3e4d93bb39.png)

Still doesn't work for me on production.  Browser differences maybe?  I've tried in Edge, Chrome, and Firefox on Windows.  No joy.

**Comment by RaphaelAlvez** [comment]
> please ignore all my previous comments. nothing was fixed. I was selecting an invisible widget that was above the pawn.....

@96LawDawg I was just selecting a basic widget that I had clean the class

**Comment by 96LawDawg** [comment]
Yeah.  Now I see you said ignore previous comments.  But this discussion did make me think about some other css modifications that screw with the highlighting.  For example, in my new Blue - Winter Alcove game, most of the holders around the room are a clip-pathed rhombus shape.  There are no borders.  When you hover over the holder with a widget, it doesn't have normal holder behavior because there is no border.  But that also means that the yellow highlights don't show up on those holders either.

**Comment by rogerl50** [comment]
@RaphaelAlvez What do you think we should do about this? Ignore and document? Fix the pawns and leave the rest to documentation?

**Comment by RaphaelAlvez** [comment]
I'm ok with documenting it

I also considered changing the highlight to be a filter so it would be more consistent and it would be "safer" for other widgets with masks.

I didn't like it because it would mess with looks of the widgets and that's very important when editing.

**Comment by ArnoldSmith86** [comment]
I agree that we should be careful with this stuff. The highlight as is can already be in the way if you want to align the selected widget to something else. Time will tell if we need a toggle or hotkey or something to hide the highlight.

**Comment by 96LawDawg** [comment]
Sadly, I already have wanted a toggle for the yellow outline. I was afraid I would be the only one who thought that so I didn’t say anything.

**Comment by rogerl50** [comment]
We could:
1) Just remove the widget highlighting
2) Add a button in the global buttons section to turn off highlighting
3) Add a hotkey of some kind to turn off highlighting
Option 1 seems like overkill. Option 3 would be fine, but we'd have to find a key combo that works on all reasonable machine architectures (there are already differences between Mac and PC that I know about). I'm not crazy about option 2, either; dedicating a button to that small function seems like overkill as well, but unless someone has a better idea...

**Comment by 96LawDawg** [comment]
Not #1.  I like the widget highlighting most of the time.  We've looked into 3 before and that is hard.  I can't think of anything else besides option 2.  It isn't really that different than the reverse sort function keys concept.  And I've never used a macro (probably should learn how to do that) and we have a button for that.  So I would vote for solution 2.

**Comment by RaphaelAlvez** [comment]
Agree.
Not 1.
We had problem with 3 before.

2 should be ok but it is getting crowded in there.

**Comment by rogerl50** [comment]
@RaphaelAlvez Do you think this should be closed now that there is a toggle to disable highlighting?

**Comment by rogerl50** [comment]
Closed as a result of #1328. Feel free to reopen if you think the problem was not adequately addressed.
